plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs111.github.io # the base hostname & protocol for your site
baseurl: "/s19"  # the subpath of your site, e.g. "/blog"

course: "CS111"
course_title: "Introduction to Computational Science"
title: "UCSB CS111 S19"
github_url: https://github.com/ucsb-cs111/s19
qtr: "S19"
quarter: "Spring 2019"

lecture_code:
   url: https://github.com/ucsb-cs111/s19-lecture-files/

start_week: 1
start_date: 2019-03-31 00:00:00.00-8:00
num_weeks: 10
extra_exam_week: true
sections:

cal_dates: >
  [
    {"label":"S19 1st day of instruction", "date":"2019-04-01" },	
    {"label":"Univ Holiday", "date":"2019-05-27" },
    {"label":"S19 instruction ends", "date":"2019-06-07" },
    {"label":"S19 finals start", "date":"2019-06-10" },
    {"label":"S19 finals end", "date":"2019-06-14" },
    {"label":"S19 qtr ends", "date":"2019-06-14" }
  ]


kramdown:
   parse_block_html: false

exclude:
  - 'vendor'
  - 'setup.sh'
  - 'jekyll.sh'
include:
  - '_pages'

timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
    ready: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/
    ready: false
  discussions:
    output: true
    permalink: /discussions/:path/
    ready: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  -
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  -
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  -
    scope:
      path: ""
      type: pa
    values:
      layout: lab
  -
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  -
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
      ready: false
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: default

head_scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML
